### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by LoryKiller** [GoodDay360/OptiPy#1]
every time I try to get the version url using:

from optipy import getUrl
```
while True:
    data = getUrl(mcversion="1.8.9",  timeout=15) 
    if "408" not in data:
        print (data)
        break
```

I get:
```
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\loren\Binary-Converter\OptifineDL ALL VERSIONS\test.py", line 4, in <module>
    data = getUrl(mcversion="1.8.9",  timeout=15)
  File "C:\Python310\lib\site-packages\optipy\GetUrl.py", line 12, in getUrl
    data = r.json()
  File "C:\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by GoodDay360** [comment]
Optifine changed their website. I will look into it and rewrite the whole script again.

**Comment by GoodDay360** [comment]
solved!
